apiVersion: v1
kind: Service
metadata:
 name: coredns-tcp-lb
 namespace: kube-system
 annotations:
    metallb.universe.tf/allow-shared-ip: "key-to-share-1.2.3.4"
spec:
  loadBalancerIP: 172.17.255.100
  selector:
   k8s-app: kube-dns
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 53
     targetPort: 53
