
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: svctarget
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
    - default
  endpoints:
#  - port: metrics
#    path: /basic_status
  - path: /metrics
    port: metrics
