apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    app: svc
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: metrics
