apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: web
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: metrics
    - name: http-status
      port: 8080
      protocol: TCP
      targetPort: 8080
