apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
 name: frontend
 namespace: microservices-demo
spec:
 hosts:
 - 51.250.90.150.xip.io
 gateways:
 - frontend
 http:
  - route:
    - destination:
        host: frontend
        port:
          number: 80
