apiVersion: v1
kind: Pod
metadata:
  name: homework
  labels:
    app: homework
spec:
  containers:
    - name: web
      image: vehpbkrby/homework1:v1
      volumeMounts:
        - mountPath: /app
          name: www
  initContainers:
    - name: init-www
      image: busybox
      command: ['sh', '-c', "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
      volumeMounts:
        - mountPath: /app
          name: www
  volumes:
    - name: www
      emptyDir: {}

