apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web
      image: vehpbkrby/homework1:v1
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-www
      image: busybox
      command: ['sh', '-c', "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}

